spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diabetici
    username: diabetici
    password: diabetici
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

security:
  jwt:
    secret: "change-me-please-super-secret-key"
    expiration: 86400000
